/*
 * CoinGecko CryptoWatcher
 * CoinGecko API for CryptoWatcher, defines the necessary endpoints for the app to work
 *
 * OpenAPI spec version: 0.0.2
 * Contact: nagygm17@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.nagygm.cryptowatcher.model

import com.google.gson.annotations.SerializedName
import java.util.*
import javax.annotation.Generated

/**
 * Image
 */
@Generated(
    value = ["io.swagger.codegen.v3.generators.java.JavaClientCodegen"],
    date = "2020-05-09T13:04:15.904459+02:00[Europe/Budapest]"
)
class Image {
    /**
     * Get thumb
     * @return thumb
     */
    @SerializedName("thumb")
    var thumb: String? = null

    /**
     * Get small
     * @return small
     */
    @SerializedName("small")
    var small: String? = null

    /**
     * Get large
     * @return large
     */
    @SerializedName("large")
    var large: String? = null
    fun thumb(thumb: String?): Image {
        this.thumb = thumb
        return this
    }

    fun small(small: String?): Image {
        this.small = small
        return this
    }

    fun large(large: String?): Image {
        this.large = large
        return this
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) {
            return true
        }
        if (o == null || javaClass != o.javaClass) {
            return false
        }
        val image = o as Image
        return thumb == image.thumb &&
                small == image.small &&
                large == image.large
    }

    override fun hashCode(): Int {
        return Objects.hash(thumb, small, large)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class Image {\n")
        sb.append("    thumb: ").append(toIndentedString(thumb)).append("\n")
        sb.append("    small: ").append(toIndentedString(small)).append("\n")
        sb.append("    large: ").append(toIndentedString(large)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}