/*
 * CoinGecko CryptoWatcher
 * CoinGecko API for CryptoWatcher, defines the necessary endpoints for the app to work
 *
 * OpenAPI spec version: 0.0.2
 * Contact: nagygm17@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.nagygm.cryptowatcher.model

import com.google.gson.annotations.SerializedName
import java.util.*
import javax.annotation.Generated

/**
 * Ping
 */
@Generated(
    value = ["io.swagger.codegen.v3.generators.java.JavaClientCodegen"],
    date = "2020-05-09T13:04:15.904459+02:00[Europe/Budapest]"
)
class Ping {
    /**
     * Get geckoSays
     * @return geckoSays
     */
    @SerializedName("gecko_says")
    var geckoSays: String? = null
    fun geckoSays(geckoSays: String?): Ping {
        this.geckoSays = geckoSays
        return this
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) {
            return true
        }
        if (o == null || javaClass != o.javaClass) {
            return false
        }
        val ping = o as Ping
        return geckoSays == ping.geckoSays
    }

    override fun hashCode(): Int {
        return Objects.hash(geckoSays)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class Ping {\n")
        sb.append("    geckoSays: ").append(toIndentedString(geckoSays)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}